title: Sir Bevis Lodge
description: Sir Bevis Lodge is a Freemasons lodge dedicated to fellowship, charity, and tradition.
author:
  name: Luke Jefferies
  email: lukejefferiesuk@gmail.com
social:
  facebook: https://www.facebook.com/groups/1025304600904180/
  email: test@gmail.com
excerpt_separator: "<!-- more -->"
permalink: /news/:title/
url: https://jefferies917.github.io
baseurl: /sirbevis.github.io