title: Sir Bevis Lodge 5072
author:
  name: Luke Jefferies
  email: lukejefferiesuk@gmail.com
social:
  facebook: https://www.facebook.com/groups/1025304600904180/
  email: lukejefferiesuk@gmail.com
excerpt_separator: "<!-- more -->"